server:
  port: 8888

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://leiren:${REGISTRY_SERVER_PASSWORD:renlei}@127.0.0.1:8761/eureka/

spring:
  profiles:  #本地配置，如果使用git则不需要配置
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:/workfile/spring-boot-cloud-master/config-repo
        #git:
          #uri: https://github.com/renlei524/spring-boot-cloud #配置git仓库地址
          #search-paths: config-repo  #配置仓库路径
          #username：349191849@qq.com #访问git仓库的用户名
          #password：r13679657748l #访问git仓库的用户密码
        #label：master #配置仓库的分支
  rabbitmq:
    host: 192.168.2.68
    username: leiren
    password: leiren
    port: 5672

security:
  basic: #可以不配置
    enabled: true
  user:
    name: admin
    password: ${CONFIG_SERVER_PASSWORD:admin}
