server:
  port: 8888

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://leiren:${REGISTRY_SERVER_PASSWORD:leiren}@127.0.0.1:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangxd1989/spring-boot-cloud
          search-paths: config-repo
  rabbitmq:
    host: 127.0.0.1

security:
  user:
    name: admin
    password: ${CONFIG_SERVER_PASSWORD:admin}
