spring:
  application:
    name: zipkin
  rabbitmq:
    host: 192.168.2.68
    username: leiren
    password: leiren
    port: 5672

server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
