server:
  port: 8761

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

security:
  basic:  #可以不配置
    enabled: true
  user:
    name: leiren
    password: ${REGISTRY_SERVER_PASSWORD:renlei}
